server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS:http://localhost:8081/eureka}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000

spring:
  application:
    name: icloud-fmf-server