server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS:http://localhost:8081/eureka}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  application:
    name: icloud-fmf-server